language: go

go:
- 1.8

# blech, Travis downloads with capitals in DirectXMan12, which confuses go
go_import_path: github.com/directxman12/k8s-prometheus-adapter

addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

install:
- make -B vendor

script: make verify

cache:
  directories:
  - ~/.glide

deploy:
  provider: script
  script: .travis-deploy.sh
  on:
    branch: master
