language: go

go:
- '1.15'

# blech, Travis downloads with capitals in DirectXMan12, which confuses go
go_import_path: github.com/directxman12/k8s-prometheus-adapter

script: make verify && git diff --exit-code

sudo: required
services:
- docker

env:
- GO111MODULE=on

deploy:
- provider: script
  script: bash .travis-deploy.sh
  on:
    branch: master
- provider: script
  script: bash .travis-deploy.sh
  on:
    tags: true
